[[server]]
name = "docker-prod0"
[server.config]
address = "https://periphery:8120"
enabled = true

##

[[server]]
name = "docker-test0"
[server.config]
address = "https://docker-test0.fritz.box:8120"
enabled = true

##

[[stack]]
name = "komodo"
[stack.config]
server = "docker-prod0"
poll_for_updates = true
linked_repo = "homelab"
run_directory = "docker/komodo"
environment = """
DOCKER_DATA_DIR=[[DOCKER_DATA_DIR]]
KOMODO_DB_USERNAME=[[KOMODO_DB_USERNAME]]
KOMODO_DB_PASSWORD=[[KOMODO_DB_PASSWORD]]
KOMODO_PASSKEY=[[KOMODO_PASSKEY]]
KOMODO_HOST=[[KOMODO_HOST]]
KOMODO_WEBHOOK_SECRET=[[KOMODO_WEBHOOK_SECRET]]
KOMODO_LOCAL_AUTH=true
KOMODO_DISABLE_USER_REGISTRATION=true
"""

##

[[stack]]
name = "periphery-prod0"
[stack.config]
server = "docker-prod0"
project_name = "periphery"
poll_for_updates = true
linked_repo = "homelab"
run_directory = "docker/periphery"
environment = """
COMPOSE_PROFILES=internal
PERIPHERY_PASSKEYS=[[PERIPHERY_PASSKEYS]]
"""

##

[[stack]]
name = "periphery-test0"
[stack.config]
server = "docker-test0"
project_name = "periphery"
poll_for_updates = true
linked_repo = "homelab"
run_directory = "docker/periphery"
environment = """
COMPOSE_PROFILES=exposed
PERIPHERY_PASSKEYS=[[PERIPHERY_PASSKEYS]]
"""

##

[[repo]]
name = "homelab"
[repo.config]
server = "docker-prod0"
builder = "local"
git_account = "theconen"
repo = "theconen/homelab"

##

[[builder]]
name = "local"
[builder.config]
type = "Server"
params.server_id = "docker-prod0"

##

[[resource_sync]]
name = "homelab"
[resource_sync.config]
linked_repo = "homelab"
resource_path = ["komodo/docker-prod0.toml"]
managed = true
delete = true