[[server]]
name = "local"
[server.config]
address = "https://periphery:8120"
enabled = true

##

[[stack]]
name = "komodo"
[stack.config]
server = "local"
poll_for_updates = true
linked_repo = "homelab"
run_directory = "docker/komodo"
environment = """
DOCKER_DATA_DIR=[[DOCKER_DATA_DIR]]
KOMODO_DB_USERNAME=[[KOMODO_DB_USERNAME]]
KOMODO_DB_PASSWORD=[[KOMODO_DB_PASSWORD]]
KOMODO_PASSKEY=[[KOMODO_PASSKEY]]
KOMODO_HOST=[[KOMODO_HOST]]
KOMODO_WEBHOOK_SECRET=[[KOMODO_WEBHOOK_SECRET]]
KOMODO_LOCAL_AUTH=true
KOMODO_DISABLE_USER_REGISTRATION=true
TRAEFIK_DOMAINNAME_1=[[TRAEFIK_DOMAINNAME_1]]
"""

##

[[stack]]
name = "nightscout"
[stack.config]
server = "local"
run_build = true
poll_for_updates = true
destroy_before_deploy = true
linked_repo = "homelab"
webhook_force_deploy = true
run_directory = "docker/nightscout"
environment = """
DOCKER_DATA_DIR=[[DOCKER_DATA_DIR]]
API_SECRET=[[NIGHTSCOUT_API_SECRET]]
NIGHTSCOUT_DB_USERNAME=[[NIGHTSCOUT_DB_USERNAME]]
NIGHTSCOUT_DB_PASSWORD=[[NIGHTSCOUT_DB_PASSWORD]]
TRAEFIK_DOMAINNAME_1=[[TRAEFIK_DOMAINNAME_1]]
"""

##

[[stack]]
name = "pangolin"
[stack.config]
server = "local"
poll_for_updates = true
destroy_before_deploy = true
linked_repo = "homelab"
run_directory = "docker/pangolin"
environment = """
DOCKER_DATA_DIR=[[DOCKER_DATA_DIR]]
TRAEFIK_DOMAINNAME_1=[[TRAEFIK_DOMAINNAME_1]]
SERVER_SECRET=[[PANGOLIN_SERVER_SECRET]]
SMTP_HOST=[[PANGOLIN_SMTP_HOST]]
SMTP_USER=[[PANGOLIN_SMTP_USER]]
SMTP_PASSWORD=[[PANGOLIN_SMTP_PASSWORD]]
SMTP_NO_REPLY_EMAIL=[[PANGOLIN_SMTP_NO_REPLY_EMAIL]]
"""

##

[[stack]]
name = "periphery"
[stack.config]
server = "local"
poll_for_updates = true
linked_repo = "homelab"
run_directory = "docker/periphery"
environment = """
COMPOSE_PROFILES=internal
PERIPHERY_PASSKEYS=[[PERIPHERY_PASSKEYS]]
"""

##

[[stack]]
name = "traefik"
[stack.config]
server = "local"
poll_for_updates = true
destroy_before_deploy = true
linked_repo = "homelab"
run_directory = "docker/traefik"
environment = """
DOCKER_DATA_DIR=[[DOCKER_DATA_DIR]]
HETZNER_API_KEY=[[TRAEFIK_HETZNER_API_KEY]]
DOMAINNAME_1=[[TRAEFIK_DOMAINNAME_1]]
DOMAINNAME_1_EMAIL=[[TRAEFIK_DOMAINNAME_1_EMAIL]]
"""

##

[[repo]]
name = "homelab"
[repo.config]
server = "local"
builder = "local"
git_account = "theconen"
repo = "theconen/homelab"

##

[[procedure]]
name = "GitOps"

[[procedure.config.stage]]
name = "Stage 1"
enabled = true
executions = [
  { execution.type = "PullRepo", execution.params.repo = "homelab", enabled = true }
]

[[procedure.config.stage]]
name = "Stage 2"
enabled = true
executions = [
  { execution.type = "RunSync", execution.params.sync = "homelab", enabled = true }
]

[[procedure.config.stage]]
name = "Stage 3"
enabled = true
executions = [
  { execution.type = "BatchDeployStackIfChanged", execution.params.pattern = "*", enabled = true }
]

##

[[alerter]]
name = "Discord"
[alerter.config]
enabled = true
endpoint.type = "Discord"
endpoint.params.url = "[[DISCORD_ALERTS_WEBHOOK]]"

##

[[builder]]
name = "local"
[builder.config]
type = "Server"
params.server_id = "local"

##

[[resource_sync]]
name = "homelab"
[resource_sync.config]
linked_repo = "homelab"
resource_path = ["komodo/docker-prod0.toml"]
managed = true
delete = true