services:
  deluge:
    image: "linuxserver/deluge:18.04.1"
    container_name: "deluge"
    restart: "unless-stopped"
    ports:
      - "44444:44444"
    volumes:
      - "${DOCKER_DATA_DIR:?error}/${COMPOSE_PROJECT_NAME:?error}/config:/config"
      - "deluge-downloads:/downloads"
      - "deluge-completed:/completed"
    environment:
      PGID: "${PGID:?error}"
      PUID: "${PUID:?error}"
      TZ: "Europe/Berlin"
      DELUGE_LOGLEVEL: "${DELUGE_LOGLEVEL:-none}"
    networks:
        proxy:
    labels:
      traefik.enable: true
      traefik.http.routers.deluge-internal.entrypoints: "websecure-internal"
      traefik.http.routers.deluge-internal.rule: "Host(`deluge.${TRAEFIK_DOMAINNAME_1:?error}`)"
      traefik.http.routers.deluge-internal.service: "deluge"
      traefik.http.services.deluge.loadbalancer.server.port: 8112
volumes:
  deluge-downloads:
    driver: "local"
    driver_opts:
      type: "cifs"
      o: "username=${SMB_USERNAME:?error},password=${SMB_PASSWORD:?error},rw,noperm,file_mode=0777,dir_mode=0777"
      device: "//${SMB_HOST:?error}/${SMB_PATH_DOWNLOADS:?error}"
  deluge-completed:
    driver: "local"
    driver_opts:
      type: "cifs"
      o: "username=${SMB_USERNAME:?error},password=${SMB_PASSWORD:?error},rw,noperm,file_mode=0777,dir_mode=0777"
      device: "//${SMB_HOST:?error}/${SMB_PATH_COMPLETED:?error}"
networks:
  proxy:
    external: true
    name: "${TRAEFIK_NETWORK_NAME:-proxy}"