services:
  periphery:
    image: "ghcr.io/moghtech/komodo-periphery:1.19.0"
    container_name: "periphery"
    labels:
      komodo.skip: # Prevent Komodo from stopping with StopAllContainers
    restart: "unless-stopped"
    security_opt:
      - "label:disable" # Periphery needs to run as root to access docker.sock and /proc, so disable SELinux labels.
      - "no-new-privileges:true"
    environment:
      - "PERIPHERY_PASSKEYS=${PERIPHERY_PASSKEYS:?error}"
      - "PERIPHERY_INCLUDE_DISK_MOUNTS=/etc/hostname"
    volumes:
      ## Mount external docker socket
      - "/var/run/docker.sock:/var/run/docker.sock"
      ## Allow Periphery to see processes outside of container
      - "/proc:/proc"
      ## Specify the Periphery agent root directory.
      ## Must be the same inside and outside the container,
      ## or docker will get confused. See https://github.com/moghtech/komodo/discussions/180.
      ## Default: /etc/komodo.
      - "${PERIPHERY_ROOT_DIRECTORY:-/etc/komodo}:${PERIPHERY_ROOT_DIRECTORY:-/etc/komodo}:Z"
