services:
  mongo:
    image: "mongo:8.0"
    container_name: "komodo-mongo"
    labels:
      komodo.skip: # Prevent Komodo from stopping with StopAllContainers
    command: "--quiet --wiredTigerCacheSizeGB 0.25"
    restart: "unless-stopped"
    volumes:
      - "${DOCKER_DATA_DIR:?error}/${COMPOSE_PROJECT_NAME:?error}/mongo-data:/data/db:z"
      - "${DOCKER_DATA_DIR:?error}/${COMPOSE_PROJECT_NAME:?error}/mongo-config:/data/configdb:z"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${KOMODO_DB_USERNAME:?error}"
      MONGO_INITDB_ROOT_PASSWORD: "${KOMODO_DB_PASSWORD:?error}"

  core:
    image: "ghcr.io/moghtech/komodo-core:1.18.4"
    container_name: "komodo-core"
    labels:
      komodo.skip: # Prevent Komodo from stopping with StopAllContainers
    restart: "unless-stopped"
    depends_on:
      - "mongo"
    ports:
      - "9120:9120"
    networks:
      - default
      - periphery
    environment:
      KOMODO_DATABASE_ADDRESS: "mongo:27017"
      KOMODO_DATABASE_USERNAME: "${KOMODO_DB_USERNAME:?error}"
      KOMODO_DATABASE_PASSWORD: "${KOMODO_DB_PASSWORD:?error}"
      KOMODO_FIRST_SERVER: "https://periphery:8120"
      KOMODO_PASSKEY: "${KOMODO_PASSKEY:?error}"
      KOMODO_HOST: "${KOMODO_HOST:?error}"
      KOMODO_WEBHOOK_SECRET: "${KOMODO_WEBHOOK_SECRET:?error}"
      KOMODO_LOCAL_AUTH: "${KOMODO_LOCAL_AUTH:-true}"
      KOMODO_DISABLE_USER_REGISTRATION: "${KOMODO_DISABLE_USER_REGISTRATION:-true}"
      TZ: "${TZ:-Europe/Berlin}"
    volumes:
      - "repo-cache:/repo-cache"
volumes:
  repo-cache:
networks:
  default:
  periphery:
    external: true
    name: ${PERIPHERY_NETWORK_NAME:-periphery_default}